using CatchingExceptions;

var exception = new CatchingEx2();

exception.Catch();